import { Alata } from "next/font/google";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
import "./globals.scss";
import Head from "next/head";

const alata = Alata({ 
  weight: '400',
  subsets: ["latin"]    
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={alata.className + ` dark`}>
      <Analytics/>
      <SpeedInsights/>
          {children}
      </body>
    </html>
  );
}
