import { Alata } from "next/font/google";
import "./globals.scss";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const alata = Alata({ 
  weight: '400',
  subsets: ["latin"] 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={alata.className + ` dark`}>
        {/* <Header/> */}
          {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
